"""Named constants used across Nebula Strike: Final Sector."""

GAME_TITLE = "Nebula Strike: Final Sector"

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
FPS = 60
MILLISECONDS_PER_SECOND = 1000.0
BACKGROUND_COLOR = (0, 0, 0)
MIN_HEALTH = 0
DEFAULT_VELOCITY = 0.0

PLAYER_WEAPON_SLOTS = 3
PLAYER_SPECIAL_SKILL_SLOTS = 1
MAX_ACTIVE_DRONES = 3

TUTORIAL_MAP_INDEX = 0
FIRST_MAP_INDEX = 1
FINAL_MAP_INDEX = 5
MAP_COUNT = 5
SPACE_ROOSTER_FIRST_MAP = 1
SPACE_ROOSTER_FINAL_MAP = 3
CHICKEN_OVERLORD_FIRST_MAP = 4
CHICKEN_OVERLORD_FINAL_MAP = 5

FEATHER_CORE_DROP_LIFETIME_SECONDS = 8.0
FEATHER_CORE_LOSS_ON_MAP_DEFEAT_PERCENT = 0.25

REPAIR_FC_COST_PER_HP = 1
WEAPON_LEVEL_1_FC_COST = 0
WEAPON_LEVEL_2_FC_COST = 120
WEAPON_LEVEL_3_FC_COST = 260

LASER_CANNON_BASE_DAMAGE = 10
PLASMA_SPREAD_BASE_DAMAGE = 7
ICE_BOLT_BASE_DAMAGE = 8
THUNDER_RAIL_BASE_DAMAGE = 14
MISSILE_SALVO_BASE_DAMAGE = 18

ATTACK_DRONE_FC_COST = 30
SHIELD_DRONE_FC_COST = 120
SUPPORT_DRONE_FC_COST = 120
BOMB_DRONE_FC_COST = 160
DRONE_TIER_1_UNLOCK = 1
DRONE_TIER_2_UNLOCK = 2
DRONE_TIER_3_UNLOCK = 3

WEAPON_BASE_DAMAGE = {
    "laser_cannon": LASER_CANNON_BASE_DAMAGE,
    "plasma_spread": PLASMA_SPREAD_BASE_DAMAGE,
    "ice_bolt": ICE_BOLT_BASE_DAMAGE,
    "thunder_rail": THUNDER_RAIL_BASE_DAMAGE,
    "missile_salvo": MISSILE_SALVO_BASE_DAMAGE,
}

WEAPON_UPGRADE_FC_COSTS = {
    1: WEAPON_LEVEL_1_FC_COST,
    2: WEAPON_LEVEL_2_FC_COST,
    3: WEAPON_LEVEL_3_FC_COST,
}

DRONE_FC_COSTS = {
    "attack": ATTACK_DRONE_FC_COST,
    "shield": SHIELD_DRONE_FC_COST,
    "support": SUPPORT_DRONE_FC_COST,
    "bomb": BOMB_DRONE_FC_COST,
}
